package database

import (
	"context"
	"os"
	"fmt"
	
	"github.com/jackc/pgx/v4/pgxpool"
)
func InitPool(dbPort string) (Database, error) {
	dbPassword := os.Getenv("DBpassword")
	dbUrl := fmt.Sprintf("postgres://postgres:%s@localhost:" + dbPort + "/slog", dbPassword)
	ctx := context.Background()
	pool, err := pgxpool.Connect(ctx, dbUrl)
	if err != nil {
		return nil, fmt.Errorf("Unable to connect to database: %v\n", err)
	}
	return  &DB{pool: pool}, nil
}


type DB struct {
	pool *pgxpool.Pool
}

func(d *DB) ConfigureDB() error {
	ctx := context.Background()
	var dbRes bool
	
	sqlQuery := "SELECT EXISTS (SELECT * FROM pg_tables WHERE tablename = 'users'); "
	err := d.pool.QueryRow(ctx, sqlQuery).Scan(&dbRes)
	if err != nil {
		return err
	}
	if dbRes == false {
		sqlQuery = "CREATE TABLE users (ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_name VARCHAR(64), email VARCHAR(255), date_created TIMESTAMP, password TEXT, description TEXT)"
		_, err = d.pool.Exec(context.Background(), sqlQuery)
		if err != nil {
			return err
		}
	}

	sqlQuery = "SELECT EXISTS (SELECT * FROM pg_tables WHERE tablename = 'posts'); "
	err = d.pool.QueryRow(ctx, sqlQuery).Scan(&dbRes)
	if err != nil {
		return err
	}
	if dbRes == false {
		sqlQuery = "CREATE TABLE posts (ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, author_id INT, content TEXT, date_created TIMESTAMP, title TEXT, tags TEXT, likes INT, FOREIGN KEY(author_id) REFERENCES users(ID))"
		_, err = d.pool.Exec(context.Background(), sqlQuery)
		if err != nil {
			return err
		}
	}
	sqlQuery = "SELECT EXISTS (SELECT * FROM pg_tables WHERE tablename = 'post_likes');"
	err = d.pool.QueryRow(ctx, sqlQuery).Scan(&dbRes)
	if err != nil {
		return err
	}
	if dbRes == false {
		sqlQuery = `CREATE TABLE post_likes (
			user_id INT NOT NULL,
			post_id INT NOT NULL,
			created_at TIMESTAMP DEFAULT NOW(),
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
			FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
			UNIQUE (user_id, post_id));`
		_, err = d.pool.Exec(context.Background(), sqlQuery)
		if err != nil {
			return err
		}
	}
	sqlQuery = "SELECT EXISTS (SELECT * FROM pg_tables WHERE tablename = 'foreign_posts'); "
	err = d.pool.QueryRow(ctx, sqlQuery).Scan(&dbRes)
	if err != nil {
		return err
	}
	if dbRes == false {
		sqlQuery = "CREATE TABLE foreign_posts (ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, content TEXT, date_created TIMESTAMP, title TEXT, tags TEXT, origin_server_adress TEXT, origin_username TEXT)"
		_, err = d.pool.Exec(context.Background(), sqlQuery)
		if err != nil {
			return err
		}
	}
	return nil
}
